easy_admin:
    site_name: '<img src="/logo.jpg" />'
    design:
        assets:
            favicon: '/favicon.ico'
        form_theme:   'vertical'
        brand_color: '#c49d1d'
        color_scheme: 'light'