easy_admin:
    entities:
        Part:
            class: AppBundle\Entity\Part
            list:
                actions:
                    - { name: 'show', label: '', icon: 'search'}
                    - { name: 'delete', label: '', icon: 'trash' }
                    - { name: 'edit', label: '', icon: 'edit' }
                fields:
                  - 'name'
                  - 'description'
                  - { property: 'kind.name', label: 'Category' }
                  - { property: 'image.url', type: 'image', label: 'Photo' }

                title: 'Parts'
            show:
                fields:
                  - 'name'
                  - 'description'
                  - 'price'
                  - { property: 'kind.name', label: 'Category' }
                  - { property: 'url', type: 'url' }
                  - { property: 'image.url', type: 'image', label: 'Photo' }



