easy_admin:
    entities:
        Tutorial:
            class: AppBundle\Entity\Tutorial
            list:
                actions:
                    - { name: 'delete', label: 'Remove', icon: 'trash' }
                    - 'edit'