<?php

namespace AppBundle\Repository;

/**
 * PartCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
