api:
    resource: "@AppBundle/Controller"
    type: annotation

easy_admin_bundle:
    resource: "@AppBundle/Controller/Admin/AdminController.php"
    type:     annotation
    prefix:   /admin

logout:
    path: /logout