# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:  { password: qwerty, roles: 'ROLE_ADMIN' }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }